<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_filtered_User</name>
   <tag></tag>
   <elementGuidId>a47b274e-e4d4-454c-b253-e4353d2e273a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;cgrid2_1564476473652&quot;)/div[@class=&quot;objbox&quot;]/table[@class=&quot;obj row20px&quot;]/tbody[1]/tr[@class=&quot;ev_dhx_web&quot;]/td[1][count(. | //td[@title = 'rshrestha' and @ref_element = 'Object Repository/Page_TRMTracker/iframe']) = count(//td[@title = 'rshrestha' and @ref_element = 'Object Repository/Page_TRMTracker/iframe'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>

//tr[contains(@class,'ev_dhx_web')]//td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body.dhxwins_vp_dhx_web.dhxlayout_base_dhx_web:nth-child(2) div.dhxlayout_cont:nth-child(5) div.dhx_cell_layout:nth-child(1) div.dhx_cell_cont_layout div.gridbox.gridbox_dhx_web.isModern div.objbox table.obj.row20px tbody:nth-child(1) tr.ev_dhx_web:nth-child(2) > td:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>rshrestha</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rshrestha</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cgrid2_1564476473652&quot;)/div[@class=&quot;objbox&quot;]/table[@class=&quot;obj row20px&quot;]/tbody[1]/tr[@class=&quot;ev_dhx_web&quot;]/td[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_TRMTracker/iframe</value>
   </webElementProperties>
</WebElementEntity>
