<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Currency</name>
   <tag></tag>
   <elementGuidId>9b9a5ea8-a2a3-476e-a2ae-31131553fff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_base</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Currency*</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dhxlayout_base_dhx_web dhxwins_vp_dhx_web&quot;]/div[@class=&quot;dhxlayout_cont&quot;]/div[@class=&quot;dhx_cell_layout&quot;]/div[@class=&quot;dhx_cell_cont_layout dhx_cell_cont_no_borders&quot;]/div[@class=&quot;dhxtabbar_base_dhx_web&quot;]/div[@class=&quot;dhxtabbar_cont&quot;]/div[@class=&quot;dhxtabbar_tabs_top&quot;]/div[@class=&quot;dhx_cell_tabbar&quot;]/div[@class=&quot;dhx_cell_cont_tabbar&quot;]/div[@class=&quot;dhxtabbar_base_dhx_web&quot;]/div[@class=&quot;dhxtabbar_cont&quot;]/div[@class=&quot;dhxtabbar_tabs_bottom&quot;]/div[@class=&quot;dhx_cell_tabbar&quot;]/div[@class=&quot;dhx_cell_cont_tabbar&quot;]/div[@class=&quot;dhxlayout_base_dhx_web&quot;]/div[@class=&quot;dhxlayout_cont&quot;]/div[@class=&quot;dhx_cell_layout&quot;]/div[@class=&quot;dhx_cell_cont_layout&quot;]/div[@class=&quot;dhxform_obj_dhx_web&quot;]/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;block_dhxform_item_label_top&quot;]/div[@class=&quot;dhxform_obj_dhx_web dhxform_block&quot;]/div[@class=&quot;dhxform_base_nested in_block&quot;]/div[@class=&quot;dhxform_base&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Setup Price Curve/Page_TRMTracker/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[8]</value>
   </webElementXpaths>
</WebElementEntity>
